### ISSUE TITLE
load save error

### ISSUE THREAD

**Issue by nirran** [sfall-team/sfall#425]
when loading this save vic is removed from party,tho i am at 3 members(and have 10 charisma),if u load the save,then go north to the crop fields map,save the game then load it,vic is removed from party,i tried to narrow what version causes it unfortunatly i went back to vrs 3.0 and same,i think it has to do with cur_map_index out of bounds,as map is num 257,tho it doesnt happen on other higher maps,this data folder is my current aned has the save in it,my master.dat is megamod vrs 2.47.6,tried with megamod vic script and vanilla vic script,also tired w/o any of my sfall scripts
https://www.mediafire.com/file/qmlnkghjakxj63z/Fallout_2.zip/file

edit : i have played with this save severaL lvls,vic didnt error,only on that specific map
edit2 : i am loath to create more issues,but with 4.3.3 this save(with above settup) ,when party members reload weapon the game crashes,does not crash with 4.3.2,to reprocude,load save and go downstairs,combat untill party member loads weap,thats it
[SLOT07.zip](https://github.com/phobos2077/sfall/files/7964935/SLOT07.zip)

**Comment by nirran** [comment]
i belive the second issue is above post is similar to this

https://www.nma-fallout.com/threads/crash-when-in-combat-in-new-reno-5-mods-in-description.220956/

**Comment by NovaRain** [comment]
The point of the crash is related to when the engine tried to get the name of an object. I cannot reproduce the crash on my basic UP/RP games, but I did get some random issues that the message doesn't show the correct item but the one in my/critter's active slots in various occasions, seems like the engine taking wrong object pointer or something.

Some examples:
* (in combat) Prostitute uses .223 Pistol. // should be Jet, the .223 pistol is in my right hand slot.
* (when I use a drug on NPC via backpack icon) You use the Power Armor on Cat Jules. // he's wearing the power armor.
* (probably not directly related) There's even one time when I use 10mm SMG to burst attack a bandit next to me, but I also got damage.

So far I couldn't find a way to reproduce the errors reliably.

**Comment by nirran** [comment]
the reload thing happens always for me,maybe that cna help?

**Comment by FakelsHub** [comment]
> https://www.nma-fallout.com/threads/crash-when-in-combat-in-new-reno-5-mods-in-description.220956/

https://github.com/FakelsHub/sFall-X/commit/e3618a38f62b4dbf5a49e457623ab08724262083
this fix seems to solve this problem.

**Comment by FakelsHub** [comment]
The message from @nirran is as usual difficult to read for me. the meaning of what was written is unclear because of his clumsy style of writing.

**Comment by NovaRain** [comment]
@nirran 
You can try [the newest develop build](https://github.com/phobos2077/sfall/suites/5186934116/artifacts/157771410) to see if it fixes the second issue.

@FakelsHub
Maybe later you could look into the [weird issue of incorrect item names](https://github.com/phobos2077/sfall/issues/425#issuecomment-1025481677) I ran into? I don't use EXTRA_WIN_MSG_CHECKS and it doesn't crash, and I had the same issue with both base and ext builds.

**Comment by nirran** [comment]
sorry FakelsHub,ill try to be clear in the future,and yes nova the party members dont crash fo2 when they reload with the test build\

**Comment by FakelsHub** [comment]
> Maybe later you could look

I can't get this behavior.

**Comment by NovaRain** [comment]
> > Maybe later you could look
> 
> I can't get this behavior.

It's a rather random occurrence. I first noticed the behavior when I was testing set_self and drop_obj (print what item is dropped from me), then when checking the save in [RPU's issue 131](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/131#issue-1082547536) it's more noticeable.

For me the incorrect "use X item on NPC" message is often (not always) displayed after I close my inventory and use items (drugs, food, etc.) on NPCs.

**Comment by FakelsHub** [comment]
> Maybe following these steps:

nothing

**Comment by NovaRain** [comment]
> > Maybe following these steps:
> 
> nothing

I'll try to make a video for reproducing the issue.

**Comment by NovaRain** [comment]
> > Maybe following these steps:
> 
> nothing

Here's the video I reproduce the issue:
[![incorrect message on item use](https://img.youtube.com/vi/Kp9B6vkeFcs/0.jpg)](https://youtu.be/Kp9B6vkeFcs)

**Comment by FakelsHub** [comment]
OK now I see the sequence. 100% reproduce.

**Comment by NovaRain** [comment]
> OK now I see the sequence. 100% reproduce.

Looks like it's due to some change in 4.3.1, with 4.3.0.2 there's no such issue.

**Comment by nirran** [comment]
this isnt fixed,i used a script that unloads all items with ammo in dudes inven and it same 'unloaded your bug" bug has a script attached that does lots of stuff,bug is vanilla bug item

**Comment by NovaRain** [comment]
You just dropped a source code that I can't compile (guess it's for megamod).
And where should I get the config file? From your autoloot mod?
If you don't like to give proper details, then don't except much response from me.

**Comment by nirran** [comment]
sorry dude,forgot the headers and i was mistaken anyway,i didnt have the correct sfall installed,disregard,bug seems to be with previous sfall
