### ISSUE TITLE
Using touchpad as mousewheel makes the game unresponsive

### ISSUE THREAD

**Issue by phobos2077** [sfall-team/sfall#443]
If UseScrollWheel is enabled and trying to scroll the main view using a touch pad on my laptop, the game becomes unresponsive:

- Key presses register with a big delay or not at all
- Mouse cursor (hex mode) seems to flicker in an unusual way

My guess: because normal mouse wheel event only happens once in a while, it works normally. But with touch pad you're supposed to scroll very smoothly, so an event fires a hundred times per second probably, and whatever code is responsible for processing the event, takes too much time to do it.

OS: Windows 11
Sfall: 4.3.6 (from Et Tu 1.8 release)
Hi-Res patch is disabled

**Comment by phobos2077** [comment]
Weirdly enough, disabling "Smart VSync" in Intel Graphics panel seems to have fixed this issue. Seems to be related to how any kind of external FPS limiters breaking the game.

**Comment by NovaRain** [comment]
Closed because the cause for the title issue is found and solved (external FPS limiters).
The further discussion about high FPS should continue in #322.
