### ISSUE TITLE
.mp4 .h264 playback support 4 Fallout 2

### ISSUE THREAD

**Issue by gustarballs1983** [sfall-team/sfall#445]
there are already projects out there that skyrocket the resolution and quality of Fallout videos especially thanks to "Topaz Labs Enhance AI for Video", however there is no way to put it back to .MVE at such resolutions. the video resolution upgrade is somewhat nessecary. especially the Fallout 1,5 Resurrection are low quality as heck ( they are not even 640x480 standard, since back then rendering software was shit, and the guys couldn't render the vids in 640x480 in a considerable timeframe, however we now have software that can easily upscale the videos without  significant quality loss, however only to mp4 .h264. Converting it to uncompressed .avi in 6 bit color without quality loss, is practically undoable, so why not enabling sfall to do the work of playing .mp4's alongside uncompressed 6 bit .avi?

**Comment by NovaRain** [comment]
sfall can already play H.264 .mp4 videos with AllowDShowMovies=1, you just need to rename them to `.avi` and have required decoders on your system.
