### ISSUE TITLE
Alt+F4 support

### ISSUE THREAD

**Issue by Owyn** [sfall-team/sfall#457]
when you close the game window with midle click during alt-tab - it asks:
![image](https://user-images.githubusercontent.com/1309656/216311779-3bd22431-ce9a-4699-b8fd-fd3be5041982.png)

and then after Yes it exits to main menu and to the desktop right after

ingame alt+x only exits to the main menu and there is no hotkey to fully exit right away - adding alt+f4 support to do that would be nice

**Comment by NovaRain** [comment]
For now if you use sfall with Mash's HRP (i.e. `HiResMode=0` in ddraw.ini), you can press Alt+F4 to fully exit the game.
