### ISSUE TITLE
ExpandWorldMap doesn't work on 1080p with scale_2X ?

### ISSUE THREAD

**Issue by Owyn** [sfall-team/sfall#458]
I tried both `ExpandWorldMap=1` and `ExpandWorldMap=0` and it looks exactly the same with the black border all around it, is there no way to expand it?

does it perhaps think my resolution is too low (cuz it's using pre-upscale resolution for calculations)?

![изображение](https://user-images.githubusercontent.com/1309656/216643151-1c91d3bb-1af8-4393-9524-f02366eb0f69.png)

**Comment by Lexx2k** [comment]
Scaling x2 duplicates the pixels, but not the resolution. As can be seen in your screenshot, that 1920x1200px is actually 960x600px and thus, too small for the expanded worldmap feature since it requires at least 890x720px.

PS: x2 scaling is shit, don't use it.

**Comment by Owyn** [comment]
> too small for the expanded worldmap feature

I just wanted the map to be fullscreen :-(

> PS: x2 scaling is shit, don't use it.

x2 is actually great, else it's a game only my pet ants would enjoy, but with x2 I can actually see what is going on on the screen

**Comment by Lexx2k** [comment]
> else it's a game only my pet ants would enjoy

Because you are setting your screen resolution too high. Make it lower and done.

**Comment by NovaRain** [comment]
You can set 1280x720 resolution and let sfall scale it to 1920x1080 fullscreen. It won't look as crisp as 2x scaling (i.e. 960x540 to 1920x1080), but at least you have the expanded world map.
![scr00000](https://user-images.githubusercontent.com/8564973/216658758-00a4e343-9cf8-46f6-9e6b-bc840b94310f.jpg)

**Comment by Owyn** [comment]
> You can set 1280x720 resolution

I tried everything just now and I could not set the 1280x720 resolution... that's too hard of a task for me it seems

f2_res.ini
```
GRAPHICS_MODE=0
SCALE_2X=0
SCR_WIDTH=1280
SCR_HEIGHT=720
```

ddraw.ini
```
Mode=6
GraphicsWidth=1280
GraphicsHeight=720
```

still it goes full 1920x1200 with ridiculously small everything:
![изображение](https://user-images.githubusercontent.com/1309656/216673019-e319276b-70ef-4e7e-93bf-f9a144310aa4.png)


but anyway, 1280x720 would still make things and especially load\new character menus smaller than now so that's why I like x2 scale

**Comment by NovaRain** [comment]
My settings are the same as yours, and I got the game in 1280x720 scaled to fit 1920x1080 fullscreen.
![scr00001](https://user-images.githubusercontent.com/8564973/216675905-144d642b-1770-42a0-802a-034835a5e4e8.jpg)
