### ISSUE TITLE
compatibility mode required to play?

### ISSUE THREAD

**Issue by Owyn** [sfall-team/sfall#459]
If I just launch the game with sfall, my mouse cursor gets stuck in the bottom-right corner and the initial resolution is stuck at 768x480 (1536x960 if I disable SCALE_2X)
![image](https://user-images.githubusercontent.com/1309656/216768797-61eef5b3-c310-4e50-83d1-365e9c7ba633.png)

I tried alt mouse input and the result is the same,
background mouse mode helps me move my mouse a bit but it still going into the right-bottom corner most of the time

only thing which helps is switching from fullscreen (not not-fullscreen) windowed DX9 mode into just fullscreen DX9 mode (then it gives and error launching the game and windows auto-applies some compatibility settings which sfall doesn't detect - and now I can play fine in the full windowed DX9 mode (tho, with some limitations in resolution)).
![image](https://user-images.githubusercontent.com/1309656/216769807-c42480a0-d29e-4dc4-ba5f-d11a2eb55abd.png)
![image](https://user-images.githubusercontent.com/1309656/216769824-1d299428-9579-41d4-b748-a5acd23c3b46.png)

am I doing something wrong?

Win 10, latest steam game version
( tried with original fallout2.exe file and latest \ not-latest sfall versions and result is the same, also had the same situation playing Fallout et tu, now with the restoration project or without it, so it's basically just sfall)
[F2_configs.zip](https://github.com/sfall-team/sfall/files/10608713/F2_configs.zip)

**Comment by NovaRain** [comment]
I have no idea what brand your mouse is, and never had that kind of issue on my gaming/testing systems. I'd try to update or uninstall its proprietary driver, see if the cursor works normally.

**Comment by NovaRain** [comment]
System/hardware related Issues like these are usually hard to reproduce and track down, as I can't possibly have all kinds of stuff people are using. I can only say I didn't encounter your issues on all my systems (I have at least five different desktops and servers to test various sfall features).
