### ISSUE TITLE
latest quicksave marked wrong due to cyclequicksave

### ISSUE THREAD

**Issue by Owyn** [sfall-team/sfall#460]
When you open the game and hit load it highlights the last saved game if you have save games paging enabled BUT if you also have cycling quicksaving enabled - it highlights not the latest but pre-pre-latest game saved for some reason

here's what I see after launching the game and hitting load button: (see that the time of auto-selected save is behind)
![image](https://user-images.githubusercontent.com/1309656/217527390-8f608dc4-27e6-41ee-acce-8626479aa837.png)

**Comment by NovaRain** [comment]
When you open Load Game screen from the main menu, it loads the position of the selected save slot from your last time exiting the Save/Load Game screens, not your last quicksave, because obviously you haven't started a quicksave session yet.

**Comment by Owyn** [comment]
Oh, I guess it was a coincidence since I chose where to save myself

but with cycling quicksaving such feature would be very appreciated (and expected)

**Comment by NovaRain** [comment]
If you already start quicksaving in the game, opening Load Game screen will select your last quicksave, I think that's enough for a game session.
