### ISSUE TITLE
Don't load the same msg file more than once in AddExtraMsgFile

### ISSUE THREAD

**Issue by phobos2077** [sfall-team/sfall#467]
If the add_extra_msg_file is called multiple times with the same file name - no need to load it every time with new ID. Cache by file name.
This might also prevent possibility for script error to overflow the whole range of possible ID's.

**Comment by NovaRain** [comment]
OK, I added a reference list to `AddExtraMsgFile()` so now there are two msg file lists. One holds actual `MessageList` structs and msg numbers, and one holds just filenames and msg numbers. I don't know if there's a better solution than the two lists moethod.
