### ISSUE TITLE
Write conflicts

### ISSUE THREAD

**Issue by phobos2077** [sfall-team/sfall#475]
- [x] `0x413E8A L:4 [Conflict] with 0x413E88 L:7`
- [x] `0x423DEB L:5 [Overwriting]`
- [x] `0x43FA9F L:4 [Overwriting]`
- [x] `0x44E7D2 L:1 [Overwriting]`
- [x] `0x44EB5B L:4 [Overwriting]`
- [x] `0x4712E3 L:1 [Overwriting]`
- [x] `0x4712E4 L:4 [Overwriting]`
- [x] `0x47136D L:1 [Overwriting]`
- [x] `0x47136E L:4 [Overwriting]`
- [x] `0x48152E L:4 [Overwriting]`
- [x] `0x4C6162 L:1 [Overwriting]`
- [x] `0x4C6163 L:4 [Overwriting]`

**Comment by phobos2077** [comment]
> 0x413e8a L:4 [Conflict] with 0x413e88 L:7

ApplyAnimationsAtOncePatches conflicts with itself. One code writes `anim_set->animations[0].animType` (L:4), other one places a jump to `check_registry_hack` (L:7) that seems to restore this to vanilla `cmp     ds:_anim_set.field_10[edx], 0Bh`. The latter one wins the conflict since it's written last.

Not sure enough how this fix work to attempt fixing.

**Comment by phobos2077** [comment]
> 0x43FA9F, 0x44EB5B, 0x48152E 

These 3 are FemaleDialogMsgs patch overwriting every time we start a new game or load a save game based on player's gender. So for male and female different strings pointers will be written (for finding msg files). 

This is working as intended.

**Comment by NovaRain** [comment]
> > 0x413e8a L:4 [Conflict] with 0x413e88 L:7
> 
> ApplyAnimationsAtOncePatches conflicts with itself. One code writes `anim_set->animations[0].animType` (L:4), other one places a jump to `check_registry_hack` (L:7) that seems to restore this to vanilla `cmp ds:_anim_set.field_10[edx], 0Bh`. The latter one wins the conflict since it's written last.
> 
> Not sure enough how this fix work to attempt fixing.

The conflict only happens in debug build, as part of the [attempt of improving animation registration](https://github.com/FalloutTeamX/sfall-Extended/commit/5c74d95b7cd76d73a5254bc519247aa94d4f2552) but disabled for release later.


All these are working as intended:

> 0x423DEB

This is part of the tweak for setting the `DAM_BACKWASH` flag for the attacker before calling compute_damage_ (was after). The one from `HOOK_COMBATDAMAGE` will overwrite the one in ScriptExtender module, which is for when no hook injected.

> 0x44E7D2

This is the flags for the game movie window. If the built-in HRP is used, it will set Exclusive and MoveOnTop flags, later in Interface module a patch will add OwnerFlag flag.

> 0x4712E3, 0x4712E4, 0x47136D, 0x47136E

These are the hook for switching hand slots. If `HOOK_INVENTORYMOVE` is injected, the ones in PartyControl module will be overwritten.

> 0x4C6162, 0x4C6163

These are for fixing the return value from `xfread_` in `db_freadInt_`. If UseFileSystemOverride is enabled, the one in BugFixes module will be overwritten by the hack in FileSystem module (which has the same fix embedded).
