### ISSUE TITLE
Jinxed trait inherits from player character to party members when party control is on

### ISSUE THREAD

**Issue by BloodNik2000** [sfall-team/sfall#492]
It is really simple to do and logical since jinxed trait affects all characters in combat. it is a suggestion to little enhancement for party control mod. Honestly, im surprised that this idea is not built in.

**Comment by NovaRain** [comment]
There's a Jinxed _perk_ which works exactly the same as the trait, so I just give controlled critters the Jinxed perk if the player has the trait/perk. If you're using sfall 4.4, replace your `sfall.dat` with this one: [sfall_dat_test.zip](https://github.com/sfall-team/sfall/files/12798442/sfall_dat_test.zip)
I didn't test it extensively but it should work as intended.
