### ISSUE TITLE
Exclude pariah dog from party control when combat control is on

### ISSUE THREAD

**Issue by BloodNik2000** [sfall-team/sfall#494]
Originally pariah dog flees from battle and it is difficult to get rid of him, but if we have a full control on this party member its breaks developers plan because it is much simplier to kill him. I think it is logical to allow control on pariah dog only when combat control mode=1 or when his pid is in pid list. I am attached modified version of the gl_partycontrol script (strings 70-72), you can use this or make your own implementation.
[gl_partycontrol.zip](https://github.com/sfall-team/sfall/files/12899047/gl_partycontrol.zip)

**Comment by NovaRain** [comment]
I'd say the party control mod itself already breaks developer's intention. If controlling the pariah dog only makes it easier to get killed (either by charging to enemies or keeping it closer to the player), it still takes lots of punishment to get rid of pariah dog, not really much an issue IMO.

**Comment by BloodNik2000** [comment]
> I'd say the party control mod itself already breaks developer's intention. If controlling the pariah dog only makes it easier to get killed (either by charging to enemies or keeping it closer to the player), it still takes lots of punishment to get rid of pariah dog, not really much an issue IMO.

I see. But what if it will be just an option in sfall-mods.ini like this - 
[modified.zip](https://github.com/sfall-team/sfall/files/12901011/modified.zip)

**Comment by NovaRain** [comment]
Thanks for the suggestion, but I prefer not to add an option or internal exception based on a specific critter. In case you ask "what about `PID_MARCUS`", he and Goris already have hardcoded handling in the engine so it's somewhat tolerable (also it's related to the hardcoded handling in the engine), but adding a new critter that isn't really bugged is another thing.
