### ISSUE TITLE
LOADSAVE: ** Error reading load function #3 data! **

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#502]
Hi, I am not sure if you can help me or not. One of the players of Fallout: Yesterday v0.5 ( https://pixeldrain.com/u/7hSDEWdk ) managed to generate a corrupt save file. sfall version used is 4.3.7.

His hardware is: Ryzen 7 7800X3D, nvidia GeForece 1080Ti, Windows 11.
Here is the attached save game: [SLOT02.zip](https://github.com/sfall-team/sfall/files/14010405/SLOT02.zip)

While trying to load from save slot 2, the action fails and the debug.log contains the following:

```
 Filename SAVEGAME\SLOT02\SAVE.DAT
 Filename SAVEGAME\SLOT02\SAVE.DAT

LOADSAVE: Load name: jan 2024 / 2
LOADSAVE: Load file header size read: 30051 bytes.
Resetting sound system...done.

Scripts: [Game Reset]
LOADSAVE: Load function #0 data size read: 0 bytes.
LOADSAVE: Load function #1 data size read: 4 bytes.
LOADSAVE: Load function #2 data size read: 2784 bytes.
LOADSAVE: in SlotMap2Game

MAP: Loading SAVED map.
Destroying RANDOM encounter map.LOADSAVE: returning 13

LOADSAVE: ** Error reading load function #3 data! **
LOADSAVE: Load function #3 data size read: 175 bytes.
```

**Comment by phobos2077** [comment]
This is not even sfallgv that got corrupted, but the main dat file? Weird.

**Comment by NovaRain** [comment]
load function `#3` is `SlotMap2Game_`, it seems some map .sav in the save is corrupted. If it's just one-off, I don't think anything can help unless someone overhauls the file save/write mechanism.

**Comment by blackpaulillyria** [comment]
Hi, thanks for looking into it. I also think nothing can be done here, for some very odd and rare reason, the save got corrupt. I will close the issue now.
