### ISSUE TITLE
A new weapon like the Molotov Cocktail?

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#515]
Is it possible to create a new weapon like the Molotov Cocktail? A weapon that would explode upon impact but do a special Dancing Flames death animation if the victim dies? I tried but couldn't get the desired behavior. My targets explode upon death even when the weapon has perk "Weapon Flameboy". It seems that there are some aspects of Molotov Cocktail which are hardcoded into the exe.

**Comment by Lexx2k** [comment]
There's already a mod that changes the molotov cocktail to deal fire damage (for years by now, in fact, probably one of the oldest). You can just copy that.

**Comment by NovaRain** [comment]
See this for an example:
https://github.com/sfall-team/sfall/commit/9bd9837a7dc9867b104a89afd91150b20bb267e0

The "Weapon Flameboy" perk does not guarantee the fire dance death anim. [It only lowers the damage threshold for more violent death anims](https://github.com/alexbatalov/fallout2-re/blob/b135fc46ef40c4aecd156f3cebcf88ec531bb8ac/src/game/actions.c#L201). If the damage type is not fire, obviously you won't get the fire dance anim.

**Comment by blackpaulillyria** [comment]
Thanks for your help, guys! So basically that mod does something similar to what is happening here at this line and I can apply that behaviour to some other weapon PID?

https://github.com/alexbatalov/fallout2-re/blob/b135fc46ef40c4aecd156f3cebcf88ec531bb8ac/src/game/actions.c#L189
