### ISSUE TITLE
(4.4.3) Random freezes

### ISSUE THREAD

**Issue by DondeEstaTuHallPass** [sfall-team/sfall#516]
Playing along with;

RPU (v.28)
RPU - Talking Heads Addon (v.3.6)
THAT - Talking Head Actually Talks (v.0.4.0)
Fo2Tweak (v.12.16)
Inventory Filter (v.2.0.3)
F2 Mechanic Mini Rework (v.1.98)

I have overwritten `ddraw.dll` and `ini` with the latest sfall, and made some changes by comparing ini comes along with RPU, as well as changing few more things to my liking. For the sake of convenience, here's the list of changes I've made in `ddraw.ini` (as oppose to default ini setting that ships with sfall installation)

`HiResMode=0`
`SpeedMultiInitial=150`
`ActionPointsBar=1`
`WorldMapTravelMarkers=1`
`ItemFastMoveKey=42`
`WorldMapSlots=21`
`VersionString=FALLOUT II 1.02d  RP 2.3.3u28`
`UseFileSystemOverride=1`
`FemaleDialogMsgs=2`
`DisplayKarmaChanges=1`
`EnableHeroAppearanceMod=1`
`SkipOpeningMovies=1`
`NPCsTryToSpendExtraAP=1`
`ExtraSaveSlots=1`
`KarmaFRMs=128,146,129,125,152,127,147,134,176`
`KarmaPoints=-1000,-750,-500,-249,250,500,750,1000`
`SpeedInventoryPCRotation=500`
`BoxBarColours=11111`
`FastShotFix=1`
`SmallFrameFix=1`
`DialogPanelAnimDelay=10`
`PipboyTimeAnimDelay=10`
`EnableMusicInDialogue=1`
`NumbersInDialogue=1`
`WorldMapFontPatch=1`
`ElevatorsFile=mods\elevators.ini`
`IniConfigFolder=mods`
`AllowUnsafeScripting=2`

The freeze does not necessarily occur during combat specifically, but rather, when I'm running around randomly. Yes, I'd really like to go more detail about this, but that's all I could say; it randomly freezes.

I run around by hold shift instead of double clicking or enabling Always Run option in the preference, and shift was bound to highlight feature in Fo2Tweaks. I noticed this and re-bound the highlight input for something else, but the game still seems to randomly freeze.

[This archive](https://github.com/sfall-team/sfall/files/14925449/JuanOccupado.zip) contains all the ini settings used for every mod I'm currently using, as well as the save file where the freeze happened.

Hope I could get any help.

**Comment by NovaRain** [comment]
All I can say is to try using a lower `NumPathNodes` setting in f2_res.ini, usually 4 or 5 should be enough.
If the random freeze still occurs, try disabling the mods one by one. Or refer to the help/comment/discussion section of those mods.
