### ISSUE TITLE
Bug with NPC tries to spend remaining AP option

### ISSUE THREAD

**Issue by DondeEstaTuHallPass** [sfall-team/sfall#524]
When NPC kills itself by getting caught by their own AOE attacks, it will temporarily "reanimate" and walk around for a bit just to spend remaining AP. Next, you get rather hilarious looking NPC's corpse that's standing normal, sometimes even playing idle animation. The game still register them as being dead, you can loot their "corpses" just fine. It just looks hilarious.

It usually happens with Hubologist vs press gang encounter where one with plasma grenade throws one too close to their own and blows themselves up.

**Comment by NovaRain** [comment]
Try this test build: [sfall-npc-retry-fix.zip](https://github.com/sfall-team/sfall/files/15164815/sfall-npc-retry-fix.zip)
It should prevent dead NPCs from trying to spend their remaining AP.

**Comment by phobos2077** [comment]
Is this sfall fault or vanilla issue?

**Comment by NovaRain** [comment]
> Is this sfall fault or vanilla issue?

It's from `NPCsTryToSpendExtraAP`.

**Comment by NovaRain** [comment]
OK, I replaced all encounters around San Fran with "Hubologists vs Press Gang" and got three times of this glitch in an hour of encounter grinding. I didn't get the glitch anymore with the code change in another hour of grinding, so I consider my fix works.
