### ISSUE TITLE
Feature Request: Double-clicking in the inventory swap GUI

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#526]
Right now, when we are looting containers or corpses and don’t want to take all the items, we have to drag the item from one inventory to the other in the inventory swap GUI. 

It would be nice if we could just double-click an item and that would instantly move it to the other inventory. So double-clicking an item from inventory on the left, would instantly move it to the innvetory on the right. And double-clicking an item from inventory on the right, would instantly move it to the invetory on the left.

**Comment by DondeEstaTuHallPass** [comment]
How about assign a key to hold fro this function? Ctrl + clicking on things instantly transfer things and all that. I'd imagine that would be easier to implement than checking double clicks on items.

**Comment by phobos2077** [comment]
I agree, Ctrl+Click should be easier to implement. But someone needs to actually do it.

**Comment by phobos2077** [comment]
Maybe Ctrl+Click can work like this:

Barter screen: there's only one way for items in a given table to go. So NPC inventory goes to NPC ask table and vice versa. PC inventory goes to PC offer table and vice versa.

Loot/steal: this is obvious, there's only 2 lists.

Inventory: items from each slot goes to main inventory. Items from inventories go to appropriate slot:
- Armor to armor slot, replacing existing, if it's not free.
- Any other item goes to next free hand slot. If both are taken, replaces item in the Right hand slot.

**Comment by phobos2077** [comment]
Implemented for loot and barter: https://github.com/sfall-team/sfall/commit/b5847532b433c0b8eff21ac4dba4e87da30703d4

**Comment by phobos2077** [comment]
For main inventory I went with @NovaRain suggestion. Armor goes to armor slot, everything else goes to current active hand slot.

**Comment by burner1024** [comment]
Maybe make configurable key?
I think middle mouse click would work well.

**Comment by phobos2077** [comment]
> Maybe make configurable key?

The key is configurable, it's Ctrl by default. But it must be a keyboard key.
