### ISSUE TITLE
HOOK AFTERHITROLL and Jinxed(and Also Slayer and Sniper)

### ISSUE THREAD

**Issue by dekrus** [sfall-team/sfall#527]
Arg0 of HOOK_AFTERHITROLL does not correspond to the result of the attack if the result was changed by perks (JINXED, Slayer, Sniper).

If a critical miss occurs due to a Jinxed check, arg0 will be 1 instead of 0.
Similarly with the critical hit of “Assassin or Sniper” arg0 = 2 instead of 3.

Also "set_sfall_return(miss|hit)" can turn into a critical miss/hit under the influence of these perks.

It seems to me that the hook should return the “real” result of the attack and be able to change it.

**Comment by phobos2077** [comment]
Well you can't change that without possibly breaking some mods.

Hook happens at this line:
https://github.com/alexbatalov/fallout2-re/blob/main/src/game/combat.c#L3765

**Comment by dekrus** [comment]
Then there is no need to change anything. It's easier to temporarily remove these perks/traits than to risk breaking mods
