### ISSUE TITLE
PlayIdleAnimOnReload=1 Causes to lose highlighting after reload in combat

### ISSUE THREAD

**Issue by xMatth3w** [sfall-team/sfall#528]
Basically title.
After enabling this settings, it will play the reload animation to a weapon, but after you reload combat highlight doesn't work and you have to press shift after every reload to higlight critters in combat. I don't know if it's a limitation of this settings or not working as inteded. 
Tested on fresh FO2 + newest Sfall

**Comment by NovaRain** [comment]
I can't seem to reproduce that in my game. In a random encounter with two group of enemies fighting each other, I shoot someone and reload (playing "idle" animation), all critters still have their combat highlight (outlines) in subsequent turns.
