### ISSUE TITLE
Ammo mod's display issue

### ISSUE THREAD

**Issue by DondeEstaTuHallPass** [sfall-team/sfall#529]
Even after enabling YAAM, or Glovz' damage fix, the description for ammo seems remain the same as that of Fallout 2 vanilla.

![Glovz](https://github.com/sfall-team/sfall/assets/166567329/f463c441-1ca3-428d-8a79-52fdfb6d4920)
This is 5mm AP description with Glovz's damage fix (same result with `DamageFormula=2` in ddraw)
I don't know what _Div: DR/1, DT/2_ supposed to represent, but the number on those two text seems to be a failed representation of displaying Fallout 2 vanilla 5mm AP round's damage modifier, which is 1/2.

![YAAM](https://github.com/sfall-team/sfall/assets/166567329/b3114b42-f273-4c81-a8a2-6ea6275a442c)
And this is for YAAM.

As for YAAM, I believe not only the description is in Fallout 2 vanilla, but ammo itself seems to work the same as Fallout 2 vanilla, as I did 0 dmg against an enclave patrolman with 5mm AP loaded Avenger Minigun, which could mean that the damage was halved like the vanilla 5mm AP.

I've read the changelog for sfall and it mentions it _"added a tweak to the ammo information in the inventory"_ for both ammo mods. Could this be the tweak it spoke of, or has there been a change to ammo mods in general?

**Comment by NovaRain** [comment]
It's because the ammo mod loader script (`gl_ammomod.int`) couldn't load the corresponding ammo INI. If you're playing RPU, it should already have `AmmoGlovz.ini` and `AmmoYAAM.ini` in the mods folder. Make sure you have the script and INI files in the folders they should, and `IniConfigFolder=mods` in ddraw.ini (or the script will only search the game root directory).

**Comment by DondeEstaTuHallPass** [comment]
I have both ammo mods' ini is rightfully in place inside mods folder, and `IniConfigFolder` is returning 'mods' as it should be as well, but I don't seem to have the ammo mod script. Is it supposed to ship with sfall as a raw file?

**Comment by NovaRain** [comment]
No, it's in the example_mods in sfall modderspack.
RPU should have it in the game root right after extraction from the installer, then it would run a batch to move it into the scrpts folder. If you don't have in the scripts folder, it's either the batch failed to run, or you were using the manual installation package but forgot to run the batch.

**Comment by DondeEstaTuHallPass** [comment]
Ah, I see. That explains why I had to troubleshoot myself about the music not playing in RP exclusive areas. So it was entirely my fault, then. My apology.
