### ISSUE TITLE
Console Messages wont show when sfall built in hires enabled

### ISSUE THREAD

**Issue by nirran** [sfall-team/sfall#533]
title says it,with mash hi res it shows messages but with built in enabled it doesnt,using 4.4.0 4.4.0.1 4.4.1  4.4.2 4.4.3 and 4.4.3.1 it doesnt show messages

oddly,i remember 4.4.1 adding messages leading me to believe it is on my end,i dont see how tho,this is my ddraw.ini with 4.4.3.1 

[ddraw.zip](https://github.com/sfall-team/sfall/files/15281564/ddraw.zip)

**Comment by NovaRain** [comment]
The `console.txt` shows messages with built-in HRP on my system.
It only outputs to the file every 20 messages, or when the game resets (load a saved game or quit to the main menu).

**Comment by nirran** [comment]
thank you,but in fo2,it isnt showing any messages

**Comment by nirran** [comment]
this may be a win11 compatibility issue,after restarting computer works for a while,ill have to do some testing,anybody here running win11 64?and if it matters my computer is new(6monthish) top of the line VENGENCE

**Comment by nirran** [comment]
meh works fine untill i open WoW
