### ISSUE TITLE
Support external save file location?

### ISSUE THREAD

**Issue by Dumbisted** [sfall-team/sfall#548]
I think it'll be convenient to use external save file locations, especially cloud drives for not only managing each game package's save files in one directory, but sharing save files between devices with same game packages. 

Still, I can manually transfer save files to other devices myself by compressing save file's folder and upload it to my cloud storage then download it on other devices, but it's kinda bothering to do it every time. If there is such function as it, that'll be much easier to do.

**Comment by phobos2077** [comment]
This can be solved potentially by installer/user: create a symlink from data\savegame to wherever you want.

**Comment by Dumbisted** [comment]
> This can be solved potentially by installer/user: create a symlink from data\savegame to wherever you want.

THIS IS A BRILLIANT SOLUTION! I had absolutely no idea that Symbolic link can works in that way :o

Anyway, I've just tried it and it's working well; so far so good. Deeply appreciate for the answer!
