### ISSUE TITLE
expanded ap bar not working

### ISSUE THREAD

**Issue by Slagar80** [sfall-team/sfall#550]
Im playing fallout et tu with a resolution of 1024X768 and the build in hd patch activated

when activating the expanded ap bar option, the amount of ap displayed when out of combat doesnt change compared to default

when in combat though the actual green lights are outside where they are supposed to be

i activated the feature mid playthrough but also started a new game with the same result

i also tried different screen resolutions but nothing worked

![Screenshot (1)](https://github.com/sfall-team/sfall/assets/169339713/486df6b6-bd0d-4ddc-848c-67fc11c978bf)

![Screenshot (2)](https://github.com/sfall-team/sfall/assets/169339713/83a9c23c-a8a6-4bf0-8aa4-3136998a38c5)

**Comment by phobos2077** [comment]
What sfall version?

**Comment by Slagar80** [comment]
In the ddraw.ini its says v.4.4.4

**Comment by phobos2077** [comment]
The actual version is displayed in the main menu, bottom right corner.

**Comment by NovaRain** [comment]
Et Tu doesn't update its sfall.dat or fo1_interface mod yet for the still in-development sfall 4.4.4.
