### ISSUE TITLE
An attempt to load a corrupt save file affects "fake_perks" in the next game loaded.

### ISSUE THREAD

**Issue by dekrus** [sfall-team/sfall#553]
1. Try to load this corrupted save file in any Fallout game with sfall v4.4.4 with or without any other mods.
 The save itself was made on a version of F:Nevada with a mod installed. The mod added a fake perk to the perk selection list.
[SLOT01.zip](https://github.com/user-attachments/files/16039020/SLOT01.zip)
<details>

![scr00011](https://github.com/sfall-team/sfall/assets/20253029/a04e4f7e-5615-498a-9714-0039f85858e5)

</details>

2.  Start a new game or load any working save and open the character sheet. We see fake perks there that shouldn't be.
<details>

![scr00007](https://github.com/sfall-team/sfall/assets/20253029/c0c7eb42-3ebc-4a7e-a844-32b074892659)

</details>
3. If you try to load a corrupt save multiple times in a row, a fake perk will be added for each load attempt the next time you load or start a new game.
    <details>

![scr00008](https://github.com/sfall-team/sfall/assets/20253029/1fb03d64-2029-4ad0-b25d-0613f8da0f25)

</details>

**Comment by NovaRain** [comment]
Try this test build: [sfall-444-test.zip](https://github.com/user-attachments/files/16039270/sfall-444-test.zip)
I changed how sfall resets the modules back to pre-4.1.4 for a more "aggressive" reset behavior.

**Comment by dekrus** [comment]
It works, fake perks are no longer added.
