### ISSUE TITLE
Memory access error.

### ISSUE THREAD

**Issue by Mulligan81** [sfall-team/sfall#554]
I've installed latest SFall (4.4.4). I've successfully compiled attached source code (as ReleaseXP) using the MS Visual C++ (2019). Now when I copy the newly created ddraw.dll to my F2 installation folder i get when starting a new game!
PLEASE HELP!
Thx in advance.

**Comment by NovaRain** [comment]
The last XP toolset from VS2017 (v141_xp) has a bug that would cause the game to crash on load in certain cases. Use VS2015 one (v140_xp) instead.
https://github.com/sfall-team/sfall/pull/513

**Comment by Mulligan81** [comment]
Ok. Big THX. I'll try!
