### ISSUE TITLE
Cursor lagging/skipping frames running Fallout Yesterday 0.6

### ISSUE THREAD

**Issue by poisshakatis** [sfall-team/sfall#556]
There's a noticeable lag when moving the mouse in the main menu in Fallout Yesterday, compared to Fallout 1 and 2 (gog).

I talked with PJ and he suggested changing the resolution, forcing the program to run on the video card, playing with color depth, changing the art cache value in fallouty.cfg, but none of them seemed to affect it. Shaders were also disabled.

Tried on Thinkpad X280 Win10

**Comment by NovaRain** [comment]
Check if your graphics driver enables Vsync or applies some fps limiter on the game and disable them.

**Comment by poisshakatis** [comment]
I don't have graphics card that has vsync, and for which I can tweak its settings. As I mentioned, Fallout 1 and 2 don't have this problem

**Comment by phobos2077** [comment]
A GPU is a GPU, integrated or discrete. And they all have some kind of driver settings. Comparing to GOG versions of FO1/2 is irrelevant because this repo is for the current sfall version.

**Comment by poisshakatis** [comment]
Okay, updated the graphics drivers through Intel's own installer and now it's smooth. Excuse me about the confusion, thank you for the patience
