### ISSUE TITLE
Fallout 1’s Pip-Boy screensaver in Fallout 2

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#557]
I am wondering if it would be possible to restore Fallout 1’s Pip-Boy screensaver inside Fallout 2’s engine?

For those not sure what I’m talking about, see this video: https://youtu.be/VGbnmLxgomE

**Comment by phobos2077** [comment]
Are you sure it's not in vanilla FO2 already? I remember seeing this recently. And I only ever use sfall'ed FO2.

**Comment by blackpaulillyria** [comment]
> Are you sure it's not in vanilla FO2 already? I remember seeing this recently. And I only ever use sfall'ed FO2.

I can’t say with 100% if I recall ever seeing it in Fallout 2 but I was surprised not being able to trigger it there. It starts fairly quickly in Fallout 1’s Pip-Boy but in Fallout 2 I can’t seem to trigger it. I’ve waited for about 5 to 10 minutes.

**Comment by NovaRain** [comment]
https://github.com/alexbatalov/fallout2-re/blob/main/src/game/pipboy.c#L2177
FO2 still has that "screensaver".

**Comment by phobos2077** [comment]
![image](https://github.com/user-attachments/assets/bc7edd49-459f-466e-82f7-e54a72fe1210)

Works for me.

**Comment by blackpaulillyria** [comment]
Alright, then it’s an issue on my end. I’ll try to figure out what’s causing it not to start.

**Comment by blackpaulillyria** [comment]
OK, it didn’t work because I had MASH’s HiRes mod enabled. Thanks for helping!
