### ISSUE TITLE
Outline Color don't work in sfall 4.4.4 that comes with FO: Sonora

### ISSUE THREAD

**Issue by eglische** [sfall-team/sfall#559]
Hi there,

I'm running sfall 4.4.4 that came along the sonora mod.

I have the issue that the standard key (and any other for that matter) not trigger the item outline when pressed, usually it's left shift i guess.

i tried to fiddle around with different colour bits mode and also with the graphic modes, but i can't seam to find the the right setting or even know if it's a grafic setting issue or if its that the key isn't recognised.

are there some necessary settings that have to be enabled that this function depends on?

some pointers would be highly appreciated
-eglische

**Comment by NovaRain** [comment]
Have you tried to set `CheckLOS=0` in sfall-mods.ini?

**Comment by eglische** [comment]
it is on CheckLOS=0 per default

**Comment by NovaRain** [comment]
The official Russian release of Sonona has no sfall at all. I don't know where you get a repacked version.
For the item highlighting feature, it needs a `sfall.dat` in the same folder as sfall (ddraw.dll), a `sfall-mods.ini` in the "mods" subfolder, and a valid DX scancode value for the `Key` setting in [Highlighting] section in sfall-mods.ini. The graphics settings should have nothing to do with it.

**Comment by eglische** [comment]
i followed the instructions of the English translation as i don't speak Russian:

https://github.com/RadMuravTeam/Fallout-Sonora-ENG

`Get the Extended Release for FO Sonora, the original won’t work. `

the key dx is correctly set, however i can try to switch the keyboard in the system settings to us to be absolutely sure that this is not the issue.

**Comment by NovaRain** [comment]
The "extended release" doesn't have the version of sfall that's supported here.

**Comment by phobos2077** [comment]
Why are you so sure you have sfall 4.4.4? Does the "Extended" version has it now as an option? I thought it came exclusively with "sfall extended".

**Comment by eglische** [comment]
well it says sfall 4.4.4 on the bottom right corner. i didn't realise how heavily it seams to be modded and repacked

i just looked up how to play sonora in english, and found the github:
https://github.com/RadMuravTeam/Fallout-Sonora-ENG

if there is a better way, i'm happy to follow it :)

**Comment by eglische** [comment]
i will try another release from another source without sfall then, thanks anyway
