### ISSUE TITLE
Make town_map function available again

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#561]
Hi, would it be possible to re-implement function `town_map` from Fallout 1? I could really use it for some "fast traveling" inside big locations. Workarounds with `load_map` or `world_map` functions are possible, of course, but this one would be more "natural".

The engine seems to support the request https://github.com/alexbatalov/fallout2-re/blob/main/src/game/scripts.c#L851

It looks like it was removed because it was refactored in Fallout 2?

**Comment by GoatBoy-11** [comment]
I second this!

**Comment by Lexx2k** [comment]
Why? Just teleport the player around and recenter the screen (not even sure if that is actually necessary).

**Comment by GoatBoy-11** [comment]
Of course, I'm aware of that. I'd just like to have to town map appear on command.

**Comment by Lexx2k** [comment]
But natively you can't even have multiple entry points to the same map on the town/world interface, so it would be pretty much useless. 

The only thing that would make sense is to add a hotkey that will transport you back to the worldmap, which for example Fo2Tweaks has. Of course with such a feature you will need to keep in mind that the player can possibly break scripted sequences and events with doing that. If you want to avoid that from happening, you will just have to script your own "fast travel" system with custom interface and whatnot (very possible).

**Comment by GoatBoy-11** [comment]
I see, I appreciate the reply. Thank you.

**Comment by blackpaulillyria** [comment]
The reasons I would use `town_map` instead of the suggested workarounds are these:

- Players are already used to how town maps work
- It’s an excuse to show that big, beautiful town map art again
- I don’t want to maintain two separate fast travel systems 

This is a nice-to-have feature, it’s not the end of the world if it never gets re-implemented. I’ll use the `world_map` solution as a workaround in the meantime, no way am I maintining two parallel systems for the same feature. Like they did with caravan encounters in Fallout 2, which I removed from Fallout Yesterday.

**Comment by phobos2077** [comment]
Maybe better to request this in CE repo instead.

**Comment by blackpaulillyria** [comment]
Sure, I’ll ask them. It won’t make a difference for us since CE doesn’t yet support FY but perhaps it will in the future.

**Comment by burner1024** [comment]
FO2tweaks has town map too.
