### ISSUE TITLE
Pip-Boy quest pagination issue

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#565]
If a location has more than 17 quests, one quest per each line, Pip-Boy will correctly paginate the list and display for example “Page 1 of 2” in the upper right corner. However, how do you actually flip to the other page? I don’t see a control button for navigating anywhere.

**Comment by NovaRain** [comment]
There should be up/down arrow buttons next to the "Status" in Pip-Boy.
![scr00005](https://github.com/user-attachments/assets/aa8b06eb-1500-45eb-bac6-b4e01b78b3f0)

**Comment by blackpaulillyria** [comment]
Apologies, those weren’t immediately visible to me! Thank you!
