### ISSUE TITLE
game_loaded() always returns 1

### ISSUE THREAD

**Issue by QuantumApprentice** [sfall-team/sfall#567]
The sfall function game_loaded() always returns 1 no matter how long the game has been running for.
Not sure if I used it incorrectly, but test code is:
```
procedure start begin
   variable temp := game_loaded();
   debug_msg("game_loaded?: " + temp);   
end
```
Tygernoot verified it with me.

**Comment by NovaRain** [comment]
Have you tried to call it for the second time in a "proper" global script that runs repeatedly?
https://github.com/sfall-team/sfall/blob/master/artifacts/scripting/sfall%20function%20notes.md#int-game_loaded
> **Returns 1 the **first time it is called after a new game or game load, and 0 any time after.**

I'm not sure what you'd expect from your test script, since you only called `game_loaded` once.

```pas
procedure start begin
   variable temp := game_loaded;
   if temp then begin
      debug_msg("game_loaded?: " + temp);
      set_global_script_repeat(60);
   end else begin
      debug_msg("game_loaded? second: " + temp);
   end
end
```
In debug log:
```
game_loaded?: 1
game_loaded? second: 0
game_loaded? second: 0
game_loaded? second: 0
game_loaded? second: 0
```
Works fine to me.

**Comment by QuantumApprentice** [comment]
Sorry, yeah I meant normal game scripts. 
The description says: "Its primary use is for global scripts, so that they know when to call set_global_script_repeat, but it can be called from normal scripts too." https://sfall.bgforge.net/other/#game_loaded
so I thought it was intended to work in a normal script. Glad I'm not the only one :P

**Comment by NovaRain** [comment]
I'm curious why you need to call `game_loaded` in normal scripts because there are already ways to limit some code to run only once on load for normal scripts, even before sfall was a thing.

**Comment by QuantumApprentice** [comment]
Oh I just ended up calling the original macro ```is_loading_game``` once I discovered this wasn't working. ```game_loaded``` was an accidental autocomplete that I thought would work once I discovered it, since the vscode plugin has a proper description implemented for it.

Looked up the behavior, verified the behavior didn't match with a 2nd person, then figured I'd open an issue so you guys can know about it :)
As far as "need", I'm spending a lot of time just poking through all the commands whenever I start making something new, so I'm never sure what works and what doesn't until I try it. I just needed something that did what ```game_loaded``` described :P

**Comment by NovaRain** [comment]
Try this test build: [sfall-gload-test.zip](https://github.com/user-attachments/files/16924863/sfall-gload-test.zip)
`game_loaded` should work the same in both global and normal scripts.

**Comment by QuantumApprentice** [comment]
Yup that seems to work, might even be better than the old macro.

This code:
```
   debug_msg("game_loaded:     " + game_loaded);
   debug_msg("is_loading_game: " + is_loading_game);
```
produced this result with v4.3.8
```
MAP: Loading SAVED map.
[Party Member 0]: None

game_loaded:     1
is_loading_game: 1
game_loaded:     1
is_loading_game: 1
Destroying RANDOM encounter map.LOADSAVE: Load function #3 data size read: 95 bytes.
...
//bunch of LOADSAVE operations
...
LOADSAVE: Total load data read: 65792 bytes.

game_loaded:     1
is_loading_game: 0
game_loaded:     1
is_loading_game: 0
game_loaded:     1
```
and these results on v4.4.4.1
```
MAP: Loading SAVED map.
[Party Member 0]: None

game_loaded:     1
is_loading_game: 1
game_loaded:     0
is_loading_game: 1
Destroying RANDOM encounter map.LOADSAVE: Load function #3 data size read: 95 bytes.
...
//bunch of LOADSAVE operations
LOADSAVE: Total load data read: 65792 bytes.

game_loaded:     0
is_loading_game: 0
game_loaded:     0
is_loading_game: 0
```
So game_loaded might be either more accurate, or getting triggered slightly ahead of, the original metarule macro.

**Comment by NovaRain** [comment]
No, `game_loaded` is never the same as vanilla `is_loading_game`. I only fixed its behavior for normal game scripts in the test build.
And `is_loading_game` is meant to be called in `map_enter_p_proc`, not `start`. At least in vanilla scripts it's never called in other procedures.
