### ISSUE TITLE
request - please add scripting function 'set_unspent_skillpoints'

### ISSUE THREAD

**Issue by nirran** [sfall-team/sfall#570]
Title says it,maybe(not gui) set the maximum saved unspent to 999?please

also wanta say kudos for the built in HRP,playe up to military base and not got the 'non responding' bug Mash HRP had

the necessity for `; Set EXTRA_WIN_MSG_CHECKS=1 to prevent the "NOT RESPONDING" error that may occur in windowed mode.
; Adds extra windows message checks to several loops during combat and fade effects.
; This setting is always enabled if ALT_MOUSE_INPUT=1.
EXTRA_WIN_MSG_CHECKS=1
`
thnx much

**Comment by NovaRain** [comment]
[`set_available_skill_points`](https://sfall-team.github.io/sfall/skills/#set_available_skill_points) opcode has been implemented since sfall 3.0.

**Comment by nirran** [comment]
whoops thnx nova
