### ISSUE TITLE
get_tile_fid not working properly on all tiles

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#571]
I discovered that function `get_tile_fid` sometimes returns value of `1` for some tiles, even if they contain a tile with a `fid` other than `1`.
This seems to happen on elevation 3, possibly others, around the edges of big maps. I will add more details about the issue as I discover them.

**Comment by NovaRain** [comment]
So it's been a week, did you find more details about the issue?
Judging from [the code of `get_tile_fid`](https://github.com/sfall-team/sfall/blob/master/sfall/Modules/Scripting/Handlers/Misc.cpp#L266), it's probably the tile data in `square[]` is incorrect on map load (not sure if it's possible), or the engine functions return wrong coordination or square number for some edge cases.

**Comment by blackpaulillyria** [comment]
Hi, I found that the issue doesn’t happen with a workaround when I break up the multi-levelled map into individual maps. 
Unless anyone wants to keep this open and try to fix it, I think it’s OK to close as the workaround is good enough solution.

**Comment by NovaRain** [comment]
What was the layout of the old map? Nearly all 200x200 hexes covered for three elevations?
And do you find the issue happened on other maps/elevations? (you only got it on one map?)

**Comment by blackpaulillyria** [comment]
Issue appeared on upper-left areas in map HDGATEST, elevation 3, tiles 8000 to 15000 from Fallout Yesterday v0.6. You can find everything needed here: https://gitlab.com/falloutfans/fallouty

**Comment by NovaRain** [comment]
> Issue appeared on upper-left areas in map HDGATEST, elevation 3, tiles 8000 to 15000 from Fallout Yesterday v0.6.

Hmm, OK, I downloaded 0.6 and checked the map in the mapper. Take tile 10032 as an example:
![scr00002](https://github.com/user-attachments/assets/47086bb4-3e7a-41ed-9a64-aa0f402bef2a)
It uses `edg5007.frm` and FID is 198 (as in `tiles.lst`).

I started the game with `StartingMap=hdgatest.map`, teleported myself to elevation 3, and used a keypress hook script to print tile FID:
```js
tmp := tile_under_cursor;
display_msg("Tile: " + tmp + ", ground fid: " + get_tile_ground_fid(tmp, dude_elevation) + ", roof fid: " + get_tile_roof_fid(tmp, dude_elevation));
```
And the result in the game:
![scr00000](https://github.com/user-attachments/assets/4a2ad2a3-47f3-4536-81ec-e1f404363a29)
Doesn't seem to have issues with `get_tile_fid`.

**Comment by blackpaulillyria** [comment]
Thanks for looking into this. Let me see what results will I get with your test case.

**Comment by blackpaulillyria** [comment]
Ok, I can confirm that if you use this code as I did, it will return 1.

`variable tile_fid = get_tile_fid(tile);`

However, if I change my code to the one you used, it works!

`variable tile_fid = get_tile_fid(((0 bwand 15) * 268435456) bwor ((elevation(dude_obj) bwand 15) * 16777216) bwor (tile bwand 16777215));`

Not sure what those bits are exactly for, but they've made the difference. Thank you!

**Comment by NovaRain** [comment]
By default, `get_tile_fid` works only at elev 0 (the first elevation):
https://sfall-team.github.io/sfall/tiles-and-paths/#get_tile_fid
If you want to check on other elevations, you need to use `get_tile_ground_fid` and `get_tile_roof_fid` macros from sfall.h.

**Comment by blackpaulillyria** [comment]
Ah, I wasn't aware of those new sfall macros. 
I'll save that documentation link for future reference.
Thank you very much! Have a great day =)
