### ISSUE TITLE
obj_on_screen returning mixed results

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#574]
How exactly does function `obj_on_screen` work? 

I tried to optimize the animate forever scripts and discovered that while the animated object is not in the screen's viewport, the function always correctly returns 0. However, when the object is inside the screen's viewport, it returns either 1 or 0. This is making optimization impossible. Is there something I'm doing wrong here?

**Comment by NovaRain** [comment]
I tested `obj_on_screen` on a tree in my game (RPU), and it seems working fine.
![scr00000](https://github.com/user-attachments/assets/8ea86e82-5400-4147-a319-b4c399e4c434)

Viewport moved away:
![scr00002](https://github.com/user-attachments/assets/0ffd7926-846b-4467-b0af-1b7d5c526eb0)

Moved back:
![scr00001](https://github.com/user-attachments/assets/f2f95648-66ba-4825-a902-b665b2e14776)

**Comment by blackpaulillyria** [comment]
Thank you for confirming. My test was done in an incorrect way, that is why it produced mixed results. I fixed the issue on my end.
