### ISSUE TITLE
Some of the mstr_ macros return "Error" string

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#575]
I was testing all the mstr_ macros in sfall.h v4.4.5.1 and found that some of them are not able to return a string from the MSG file they are pointing to. So they return "Error". These are:

```
mstr_custom
mstr_inventry
mstr_lsgame
mstr_options
mstr_pipboy
mstr_quests
mstr_skilldex
mstr_worldmap
mstr_character
```

**Comment by NovaRain** [comment]
These .msg files are only loaded when their corresponding interfaces are opened (and the game unloaded them on interface close):
```pas
// Party member combat control panel
display_msg("mstr_custom 104: " + mstr_custom(104));
// Player inventory screen
display_msg("mstr_inventry 50: " + mstr_inventry(50));
// Load/Save Game screen
display_msg("mstr_lsgame 108: " + mstr_lsgame(108));
// Options menu
display_msg("mstr_options 1001: " + mstr_options(1001));
// Pipby screen
display_msg("mstr_pipboy 107: " + mstr_pipboy(107));
display_msg("mstr_quests 130: " + mstr_quests(130));
// Skilldex menu
display_msg("mstr_skilldex 109: " + mstr_skilldex(109));
// This works for me when in normal game
display_msg("mstr_worldmap 600: " + mstr_worldmap(600));
// Character screen
display_msg("mstr_character 5006: " + mstr_character(5006));
```
Here's my test script: [gl_0keytest.zip](https://github.com/user-attachments/files/18183826/gl_0keytest.zip)
Press semicolon key to print the lines from [RPU .msg files](https://github.com/BGforgeNet/Fallout2_Restoration_Project/tree/master/data/text/english/game).

**Comment by blackpaulillyria** [comment]
Is there an alternative way to access those MSGs before their screens load?

**Comment by NovaRain** [comment]
> Is there an alternative way to access those MSGs before their screens load?

You can add them as extra game msgs.
https://sfall-team.github.io/sfall/sfall-funcx-macros/#add_extra_msg_file
```pas
// works outside of char screen
tmp := add_extra_msg_file("editor.msg");
display_msg("Added editor.msg as extra msg: " + tmp);
display_msg("Extra editor.msg 5006: " + message_str_game(tmp, 5006));
```

**Comment by blackpaulillyria** [comment]
Thank you for your help, that's a great workaround!
