### ISSUE TITLE
Odd Talking Heads behaviour 

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#576]
We noticed odd behavior related to Talking Heads.
Basically, they sometimes do not load at all for spoken lines.

We ruled out that this issue has anything to do with ACM file, LIP file, FRM files, MSG indexes, MSG comments, SSL code. Unless we overlooked something, we're out of ideas how to deal with this issue.

**How to replicate**

1) download and install Fallout Yesterday v0.65 https://gofile.io/d/xPzWj3
2) change `StartingMap` to `mvcanyo3.map`
3) Start a new game using some character with average INT. Premade character no. 2 is a good option
3) Talk to Alexandra choosing these dialogue options: `1,1,1`
4) Enter the cave
5) Talk to Blackjack choosing these dialogue options: `1,1,1,1,5,1,1`
6) Wait for him to exit the cave
7) Exit the cave and talk to Alexandra again. Note that her TH doesn't show up until her voiced line ends
8) Save the game
9) Exit and shutdown the exe
10) Start the exe, load the save game and note that her TH now shows up properly

**Comment by NovaRain** [comment]
I guess it's about Blackjack's talking head being unfinished. The debug log I got when I talked to him:
```
Initial Reaction == 30
ERROR: Art file not found: art\heads\blkjkgp.frm
failure!
Cache stats are disabled.
```
Even if I use the 0 key to exit the dialogue right after talking to him, Alexandra's TH still has that behavior.
If I remove the talking head in his script, Alexandra's TH works just fine.

**Comment by blackpaulillyria** [comment]
Thank you so much for getting to the bottom of this! I would have never guessed that the TH system is interconnected in such a way. All the best in 2025!
